---
title: 'Good news! CUBE is part of a successful grant application to Genome Canada’s Genomics Applications Partnership Program (GAPP).'
output: 
  html_document:
    theme: 
      version: 4
    css: styles.css
---


On May 30, 2024, Genome Canada gave the green light to a project that aims to harness the power of citizen science by using video games to process massive metagenomic data sets. The project will be led by computer science professor Dr. Jérôme Waldispühl from McGill University and Co-Studio Head Director of Operations Sébastien Caisse from Gearbox Studio Québec, the makers of the popular Borderlands video game, in partnership with the Scientific Director of the CUBE consortium, Dr. Rees Kassen of McGill University. CUBE will supply genomic information from swabs  so that gamers can help identify the antimicrobial resistance genes and organisms of highest concern in hospital settings. Genome Canada's funding will provide substantial support to galvanize CUBE initiatives at Sinai Health, Ottawa Hospital, and the Sault Area Hospital.

Borderlands 4 is the latest Massive Multiplayer Online Game (MMOG) in development by Gearbox. Its predecessor, Borderlands 3, featured the mini game Borderlands Science––the product of Waldisphühl and Caisse’s previous GAPP project which proved that simple video game puzzles could be used to tap into a vast supply of human resources (i.e., millions of users) to manually curate sequence alignments and dramatically accelerate data collection. It was estimated that Borderlands Science participants accomplished 160 years-worth of manual sequence alignment curation, a task considered impossible for a small study team and highly prone to errors if conducted computationally.
The Borderlands Science 2 mini game is the focus of this year’s GAPP project. It will prompt users to map antimicrobial resistance genes using data from environmental samples supplied by the Earth Microbiome Project (EMP) and CUBE. Specifically, CUBE will be involved by supplying genomic information from swabs obtained from surfaces in hospital settings. Users will be tasked to help arrange and classify metagenome-assembled genomes (MAGs) from the genetic material found on these swabs. These MAGs will then help CUBE studies characterize the biodiversity of microorganisms and survey the appearance of pathogens on surfaces in this high-risk setting.

In addition to being featured on the Borderlands 4 console game, Borderlands Science 2 will also be launched as a mobile game to increase accessibility and engagement by users of Borderlands 4. 
