---
title: "Coronavirus in the Urban Built Environment"
output: 
  html_document:
    theme: 
      version: 4
    css: styles.css
    toc: false
---


```{r setup, include=F}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE, collapse = TRUE)
```

```{r meta, results='asis'}
# <meta> tags to add to <head>
# these are various tags that provide info about our site
description_text <- "The COVID-19 in the Urban Built Environment (CUBE) project seeks to develop environmental sampling as a spatially-resolved method for monitoring COVID-19 in congregate settings such as long-term care homes (LTC), universities, public schools, and daycares. "

metathis::meta() |> 
  metathis::meta_viewport() |> 
  # keep this meta tag for google search indexing
  metathis::meta_name("google-site-verification" = "2hjin2NTF-SVY6SAw-HRZcg1Z-q5iNEbwHOTW4yfIao") |> 
  metathis::meta_general(
    application_name = 'COVID-19 in the Urban Built Environment',
    description = description_text,
    robots = 'index',
    subject = "COVID-19 SARS-CoV-2 environmental microbiology epidemiology urban built environment Ontario",
    rating = "General"
  ) |>
  metathis::meta_social(
    title = "COVID-19 in the Urban Built Environment",
    url = "https://cube-ontario.github.io",
    image = "https://cube-ontario.github.io/public/img/infographic.png",
    image_alt = description_text,
    og_type = "website",
    og_site_name = "COVID-19 in the Urban Built Environment",
    og_author = c("CUBE research group"),
    twitter_card_type = "summary_large_image",
    disable_pinterest = TRUE
  )

```

<head>
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-8F9R0B5L51"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-8F9R0B5L51');
</script>
</head> 

#### Developing environmental sampling as a method for monitoring SARS-CoV-2 in congregate settings

------------------------------------------------------------------------

<!-- youtube video embedding -->

::: {.video-container style="display: flex; text-align: center; margin: 0 auto; padding: 1rem;"}

<iframe width="560" height="315" style="display: block; margin: 0 auto;" src="https://www.youtube.com/embed/oVdM8T9QVmo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>

:::

------------------------------------------------------------------------

::: {#contact-cards}
```{r}
# add a new line to add a new card on the front page
# >> "card title...", "card text...", "link: either local file name or url"
tibble::tribble(
  ~title, ~text, ~link,
  "CUBE At Your Facility", " To arrange for CUBE testing in your facility, please contact us.", "contact.html",
  "Join The CUBE Reseach Group", "If you are interested in contributing to the CUBE research project, please get in touch.", "contact.html"
) |> 
  # map data into nice html cards with responsive bootstrap layout
  bs4cards::cards(
    title = title,
    text = text,
    link = link,
    spacing = 4, # space between cards
    width = 4    # relative sizing (1 narrow - 5 wide)
  )
```
:::

------------------------------------------------------------------------
